line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "W", "D"]
ignore = [
    "D203",  # no blank line before class
    "D213",  # multi-line docstring summary on first line
]

[lint.pydocstyle]
convention = "google"

[tool.ruff]
ignore = ["E722", "TID252"]