name: Validate with hassfest

on:
  push:
  pull_request:

permissions: {}

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Move files to where hassfest expects them"
        run: |
          mkdir -p custom_components/idf_mobilite_assistant
          find . -maxdepth 1 -not -name 'custom_components' -not -name '.' -exec mv {} custom_components/idf_mobilite_assistant/ \;

      - name: "Run hassfest"
        uses: home-assistant/actions/hassfest@master