name: Validate with hassfest

on:
  push:
  pull_request:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

      - name: Create HA-like structure
        run: |
          mkdir -p custom_components/idf_mobilite_assistant
          mv -r steps custom_components/idf_mobilite_assistant/
          mv -r utils custom_components/idf_mobilite_assistant/
          mv const.py custom_components/idf_mobilite_assistant/
          mv config_flow.py custom_components/idf_mobilite_assistant/
          mv sensor.py custom_components/idf_mobilite_assistant/
          mv __init__.py custom_components/idf_mobilite_assistant/
          mv manifest.json custom_components/idf_mobilite_assistant/